export const FETCH_TRIPS_STARTED = "FETCH_TRIPS_STARTED";
export const FETCH_TRIPS_SUCCESS = "FETCH_TRIPS_SUCCESS";
export const FETCH_TRIPS_FAILURE = "FETCH_TRIPS_FAILURE";

export const POINTS_PASSED = "POINTS_PASSED";
export const POINTS_MARKERS = "POINTS_MARKERS";

export const FETCH_STOPS_STARTED = "FETCH_STOPS_STARTED";
export const FETCH_STOPS_SUCCESS = "FETCH_STOPS_SUCCESS";
export const FETCH_STOPS_FAILURE = "FETCH_STOPS_FAILURE";

export const SELECTED_TRIP = "SELECTED_TRIP";
