const DEFAULT_CENTER_LATITUDE = parseFloat(30.567816);
const DEFAULT_CENTER_LONGITUDE = parseFloat(114.0201949);

export const DEFAULT_CENTER_MAP = [DEFAULT_CENTER_LATITUDE, DEFAULT_CENTER_LONGITUDE];
export const ZOOM = parseInt('11');